spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wlzx.1358
    url: jdbc:mysql://localhost:3306/gkos?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    druid:
      initial-size: 5
      max-active: 10
      use-ping-method: false

mybatis-plus:
  type-aliases-package: com.linxi.gkos.pojo.po