logging:
  level:
    #设置日志级别
    root: info
    com.linxi.gkos.mapper: debug
    com.linxi.gkos.controller: debug
  #config: classpath:log4j2.xml   自定义配置路径

  #设置日志组
  group:
    project:
      - com.linxi.gkos.mapper
      - com.linxi.gkos.controller